---
title: ""
Author: "Maggie Vincent"
Term: Fall 2020
Course: Reproducible Research in R
output: pdf_document
---

# Read in Data from BioTime - Adult Single study
# An additional study with damselfly larval data will be read in the same way
## this was downloaded from 'http://biotime.st-andrews.ac.uk/taxa.php?10' on 4 October 2020
## study name == 'The development of dragonfly communities and the consequences of territorial behaviour'
## study ID == ''
## BioTIME does not have an API, making this necessary


DataSingleStudy <- read.csv("~/GitHub/rrirfinalproject/DataSingleStudy")
rawDragonfly <- `DataSingleStudy`

install.packages('plyr')
install.packages('dplyr')

library('plyr')
library('dplyr')

cPuella <- dplyr::filter(rawDragonfly, GENUS_SPECIES == 'Coenagrion puella')
iElegans <- dplyr::filter(rawDragonfly, GENUS_SPECIES == 'Ischnura elegans')
lSponsa <- dplyr::filter(rawDragonfly, GENUS_SPECIES == 'Lestes sponsa')
lQuadrimaculata <- dplyr::filter(rawDragonfly, GENUS_SPECIES == 'Libellula quadrimaculata')
sStriolatum <- dplyr::filter(rawDragonfly, GENUS_SPECIES == 'Sympetrum striolatum')

# Make a rough plot to visualize the data

par(mfrow=c(2,3))
plot(iElegans$YEAR, iElegans$ABUNDANCE)
plot(cPuella$YEAR, cPuella$ABUNDANCE)
plot(lSponsa$YEAR, lSponsa$ABUNDANCE)
plot(lQuadrimaculata$YEAR, lQuadrimaculata$ABUNDANCE)
plot(sStriolatum$YEAR, sStriolatum$ABUNDANCE)

# I don't like that the y-axes are scaled differently and I want to change the axis labels 



# subsetting down the data.frames, since I need to do it more than once, I'll write a simple function

getAbundanceYear <- function(dat, x = 'ABUNDANCE', y = 'YEAR'){
                    tmp <- subset(dat, select = c(x, y))
                    return(tmp)
}

iElegansAY <- getAbundanceYear(iElegans)
cPuellaAY <- getAbundanceYear(cPuella)
lSponsaAY <- getAbundanceYear(lSponsa)
lQuadrimaculataAY <- getAbundanceYear(lQuadrimaculata)
sStriolatumAY <- getAbundanceYear(sStriolatum)


# I want to rename the abundance column with species name to aid comparison and readibility

iElegansSAY <- dplyr::rename(iElegansAY, iElegansAbundance = ABUNDANCE)
cPuellaSAY <- dplyr::rename(cPuellaAY, cPuellaAbundance = ABUNDANCE)
lSponsaSAY <- dplyr::rename(lSponsaAY, lSponsaAbundance = ABUNDANCE)
lQuadrimaculataSAY <- dplyr::rename(lQuadrimaculataAY, lQuadrimaculataAbundance = ABUNDANCE)
sStriolatumSAY <- dplyr::rename(sStriolatumAY, sStriolatumAbundance = ABUNDANCE)



# the current data.frames are different lengths
# this is because the years without observations of the species were not put in as zeroes
# after consultation with Tad Dallas, I will be changing the data.frames to length 27 (observation years) with zeroes for the missing years


row1959 <- c(0, 1959)
row1960 <- c(0, 1960)
row1961 <- c(0, 1961)
row1962 <- c(0, 1962)
row1963 <- c(0, 1963)

row1972 <- c(0, 1972)
row1974 <- c(0, 1974)

cPuellaCompAY <- rbind(row1959, row1960, row1961, row1962, cPuellaSAY)
iElegansCompAY <- rbind(row1959, row1960, row1961, iElegansSAY)
lSponsaCompAY <- rbind(row1959, row1960, row1961, row1962, row1963, lSponsaSAY)
# lQuadrimaculata will be dealt with differently because it is missing rows within the dataframe
sStriolatumCompAY <- rbind(row1959, row1960, row1961, sStriolatumSAY)

prelibellulaCompAY <- rbind(row1960, row1972, row1974, lQuadrimaculataSAY)
# this will add the rows I want, but now in chronological order
lQuadrimaculataCompAY <- dplyr::arrange(prelibellulaCompAY, YEAR)


# there are species missing from this dataset, they need to be added separately, I will source (and cite) the abundance data
# also need a vector corresponding to the years

YEAR <- c(1959:1988)

bPratenseAbundance <- c(0,0,0,0,0,0,0,0,0,1,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0)
pNymphulaAbundance <- c(0,0,3,20,18,5,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0)
aCyaneaAbundance <- c(0,0,0,0,1,2,3,1,1,2,3,1,5,1,2,0,0,0,1,1,1,0,2,1,1,3,1,2,2,2)
sSanguineumAbundance <- c(0,0,0,0,0,1,0,0,1,0,2,0,1,0,0,1,0,1,4, 11, 3, 0, 1, 9, 6, 10, 4, 9, 3, 4)
aGrandisAbundance <- c(0,0,0,0,0,0,0,4,0,1,1,0,2,0,2,0,0,0,1,1,0,1,2,1,0,1,1,4,0,1)

bPratenseCompAY <- data.frame(bPratenseAbundance, YEAR)
pNymphulaCompAY <- data.frame(pNymphulaAbundance, YEAR)
aCyaneaCompAY <- data.frame(aCyaneaAbundance, YEAR)
sSanguineumCompAY <- data.frame(sSanguineumAbundance, YEAR)
aGrandisCompAY <- data.frame(aGrandisAbundance, YEAR)

# I am going to join these 10 dataframes by the common column year
# I want year on the far left so I am going to reorder the first dataframe that will determine the order of my join function

bPratenseCompAY2 <- subset(bPratenseCompAY, select = c(2,1))

join1 <- dplyr::left_join(bPratenseCompAY2, pNymphulaCompAY, by= NULL)
join2 <- dplyr::left_join(join1, aCyaneaCompAY, by = NULL)
join3 <- dplyr::left_join(join2, sSanguineumCompAY, by = NULL)
join4 <- dplyr::left_join(join3, aGrandisCompAY, by = NULL)
join5 <- dplyr::left_join(join4, cPuellaCompAY, by = NULL)
join6 <- dplyr::left_join(join5, iElegansCompAY, by = NULL)
join7 <- dplyr::left_join(join6, lSponsaCompAY, by = NULL)
join8 <- dplyr::left_join(join7, lQuadrimaculataCompAY, by = NULL)
fullAbundanceDF <- dplyr::left_join(join8, sStriolatumCompAY, by = NULL)

# I want a total for each year

abundanceSums <- data.frame(rowSums(fullAbundanceDF[,c(2,3,4,5,6,7,8,9,10,11)]))
abundance_year <- cbind(abundanceSums, new_col = YEAR)
abundanceYearSums <- subset(abundance_year, select = c(2,1))

abunYearSums_1 <- dplyr::rename(abundanceYearSums, year = new_col)
abunYearsSums <- dplyr::rename(abunYearSums_1, total_abundance = rowSums.fullAbundanceDF...c.2..3..4..5..6..7..8..9..10..11...)


par(mfrow=c(1,1))
plot(abunYearsSums$year, abunYearsSums$total_abundance, xlab = "Year", ylab = "Abundance")
abline(lm(abunYearsSums$total_abundance ~ abunYearsSums$year), col="red")

fitTotal <- lm(abunYearsSums$total_abundance ~ abunYearsSums$year)

summary(fitTotal)

pValueTotal <- 0.000162

# I want plots for all 10 species with a trend line

par(mfrow=c(2,5))
plot(bPratenseCompAY$YEAR, bPratenseCompAY$bPratenseAbundance, main = "Brachytron pratense", xlab = "Year", ylab = "Abundance")
abline(lm (bPratenseCompAY$bPratenseAbundance ~ bPratenseCompAY$YEAR), col="red")

plot(pNymphulaCompAY$YEAR, pNymphulaCompAY$pNymphulaAbundance, main = "Pyrrhosa nymphula", xlab = "Year", ylab = "Abundance")
abline(lm (pNymphulaCompAY$pNymphulaAbundance ~ pNymphulaCompAY$YEAR), col="red")

plot(aCyaneaCompAY$YEAR, aCyaneaCompAY$aCyaneaAbundance, main = "Aeshna cyanea", xlab = "Year", ylab = "Abundance")
abline(lm(aCyaneaCompAY$aCyaneaAbundance ~ aCyaneaCompAY$YEAR), col="red")

plot(sSanguineumCompAY$YEAR, sSanguineumCompAY$sSanguineumAbundance, main = "Sympetrum sanguineum", xlab = "Year", ylab = "Abundance")
abline(lm(sSanguineumCompAY$sSanguineumAbundance ~ sSanguineumCompAY$YEAR), col="red")

plot(aGrandisCompAY$YEAR, aGrandisCompAY$aGrandisAbundance, main = "Aeshna grandis", xlab = "Year", ylab = "Abundance")
abline(lm(aGrandisCompAY$aGrandisAbundance ~ aGrandisCompAY$YEAR), col="red")

plot(cPuellaCompAY$YEAR, cPuellaCompAY$cPuellaAbundance, main = "Coenagrion puella", xlab = "Year", ylab = "Abundance")
abline(lm(cPuellaCompAY$cPuellaAbundance ~ cPuellaCompAY$YEAR), col="red")

plot(iElegansCompAY$YEAR, iElegansCompAY$iElegansAbundance, main = "Ischnura elegans", xlab = "Year", ylab = "Abundance")
abline(lm(iElegansCompAY$iElegansAbundance ~ iElegansCompAY$YEAR), col="red")

plot(lSponsaCompAY$YEAR, lSponsaCompAY$lSponsaAbundance, main = "Lestes sponsa", xlab = "Year", ylab = "Abundance")
abline(lm(lSponsaCompAY$lSponsaAbundance ~ lSponsaCompAY$YEAR), col="red")

plot(lQuadrimaculataCompAY$YEAR, lQuadrimaculataCompAY$lQuadrimaculataAbundance, main = "Libellula quadrimaculata", xlab = "Year", ylab = "Abundance")
abline(lm(lQuadrimaculataCompAY$lQuadrimaculataAbundance ~ lQuadrimaculataCompAY$YEAR), col="red")

plot(sStriolatumCompAY$YEAR, sStriolatumCompAY$sStriolatumAbundance, main = "Sympetrum striolatum", xlab = "Year", ylab = "Abundance")
abline(lm(sStriolatumCompAY$sStriolatumAbundance ~ sStriolatumCompAY$YEAR), col="red")


# I want to see if these are significant, so I am going to save the lm and then I will do a summary of each one

fitBPratense <- lm(bPratenseCompAY$bPratenseAbundance ~ bPratenseCompAY$YEAR)
summary(fitBPratense)
pValueBPratense <- 0.5911

fitPNymphula <- lm(pNymphulaCompAY$pNymphulaAbundance ~ pNymphulaCompAY$YEAR)
summary(fitPNymphula)
pValuePNymphula <- 0.02333

fitACyanea <- lm(aCyaneaCompAY$aCyaneaAbundance ~ aCyaneaCompAY$YEAR)
summary(fitACyanea)
pValueACyanea <- 0.3033

fitSSanguineum <- lm(sSanguineumCompAY$sSanguineumAbundance ~ sSanguineumCompAY$YEAR)
summary(fitSSanguineum)
pValueSSanguineum <- 0.00009631

fitAGrandis <- lm(aGrandisCompAY$aGrandisAbundance ~ aGrandisCompAY$YEAR)
summary(fitAGrandis)
pValueAGrandis <- 0.1363

fitCPuella <- lm(cPuellaCompAY$cPuellaAbundance ~ cPuellaCompAY$YEAR)
summary(fitCPuella)
pValueCPuella <- 8.362e-07

fitIElegans <- lm(iElegansCompAY$iElegansAbundance ~ iElegansCompAY$YEAR)
summary(fitIElegans)
pValueIElegans <- 0.103

fitLSponsa <- lm(lSponsaCompAY$lSponsaAbundance ~ lSponsaCompAY$YEAR)
summary(fitLSponsa)
pValueLSponsa <- 0.0001868

fitLQuadrimaculata <- lm(lQuadrimaculataCompAY$lQuadrimaculataAbundance ~ lQuadrimaculataCompAY$YEAR)
summary(fitLQuadrimaculata)
pValueLQuadrimaculata <- 0.0359

fitSStriolatum <- lm(sStriolatumCompAY$sStriolatumAbundance ~ sStriolatumCompAY$YEAR)
summary(fitSStriolatum)
pValueSStriolatum <- 0.9176



# I want to know how many species there are in a given year, using the nrow function from base
# I will save each as with a corresponding year identifier because I have not yet decided what format I want them all in (dataframe, table, etc.)

ASpecies <- length(which(fullAbundanceDF[1,2:11] != 0))
BSpecies <- length(which(fullAbundanceDF[2,2:11] != 0))
CSpecies <- length(which(fullAbundanceDF[3,2:11] != 0))
DSpecies <- length(which(fullAbundanceDF[4,2:11] != 0))
ESpecies <- length(which(fullAbundanceDF[5,2:11] != 0))
FSpecies <- length(which(fullAbundanceDF[6,2:11] != 0))
GSpecies <- length(which(fullAbundanceDF[7,2:11] != 0))
HSpecies <- length(which(fullAbundanceDF[8,2:11] != 0))
ISpecies <- length(which(fullAbundanceDF[9,2:11] != 0))
JSpecies <- length(which(fullAbundanceDF[10,2:11] != 0))
KSpecies <- length(which(fullAbundanceDF[11,2:11] != 0))
LSpecies <- length(which(fullAbundanceDF[12,2:11] != 0))
MSpecies <- length(which(fullAbundanceDF[13,2:11] != 0))
NSpecies <- length(which(fullAbundanceDF[14,2:11] != 0))
OSpecies <- length(which(fullAbundanceDF[15,2:11] != 0))
PSpecies <- length(which(fullAbundanceDF[16,2:11] != 0))
QSpecies <- length(which(fullAbundanceDF[17,2:11] != 0))
RSpecies <- length(which(fullAbundanceDF[18,2:11] != 0))
SSpecies <- length(which(fullAbundanceDF[19,2:11] != 0))
TSpecies <- length(which(fullAbundanceDF[20,2:11] != 0))
USpecies <- length(which(fullAbundanceDF[21,2:11] != 0))
VSpecies <- length(which(fullAbundanceDF[22,2:11] != 0))
XSpecies <- length(which(fullAbundanceDF[23,2:11] != 0))
YSpecies <- length(which(fullAbundanceDF[24,2:11] != 0))
ZSpecies <- length(which(fullAbundanceDF[25,2:11] != 0))
AASpecies <- length(which(fullAbundanceDF[26,2:11] != 0))
ABSpecies <- length(which(fullAbundanceDF[27,2:11] != 0))
ACSpecies <- length(which(fullAbundanceDF[28,2:11] != 0))
ADSpecies <- length(which(fullAbundanceDF[29,2:11] != 0))
AESpecies <- length(which(fullAbundanceDF[30,2:11] != 0))



# read in Odonate names, this is a .csv in the github repo

odonata_names <- read.table("~/GitHub/rrirfinalproject/odonata_names.csv")






